In [1]:
# Importing Libraries
import numpy as np
import pandas as pd
# Loading DataFrame

# Required Library
import pickle

file = "pklFilescontents/DATAFRAME.pkl"
fileobj = open(file, 'rb')
df = pickle.load(fileobj)
fileobj.close()

print(type(df))
df.head()

<class 'pandas.core.frame.DataFrame'>


Headline  Category  \
0  congress leader jairam ramesh object flight an...  politics   
1  bjp spokesman sambit patra call cm arvind kejr...  politics   
2  congress leader abhishek dutt react delhi cm a...  politics   
3  video pm modi call hindutva mere play card use...  politics   
4  bihar cm nitish kumar said congress `` interes...  politics   

   ENCODED_CATEGORY  
0                 2  
1                 2  
2                 2  
3                 2  
4                 2

In [2]:
# News Headlines
X = df['Headline']

# Encoded News Category
y = df['ENCODED_CATEGORY']

In [3]:
# Splitting the dataset into Training set & Testing set

# Required Library
from sklearn.model_selection import train_test_split

# Testing_set = 25%  and  Training_set = 75%
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size = 0.25, random_state = 51)

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Instantiating TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()

# Fitting & Tranforming Training Data (X_train)
tfidf_X_train = tfidf_vectorizer.fit_transform(X_train.values)

# Tranforming Testing Data (X_test)
tfidf_X_test = tfidf_vectorizer.transform(X_test.values)

# Saving tfidf_vectorizer
pickle.dump(tfidf_vectorizer, open("pklFilescontents/tfidf_vectorizer.pkl","wb"))

In [10]:
# Multinomial Naive Bayes Classifier

# Required Library
from sklearn.naive_bayes import MultinomialNB

# Instantiating Naive Bayes Classifier with alpha = 1.0
nb_classifier = MultinomialNB()

# Fitting nb_classifier to Training Data
nb_classifier.fit(tfidf_X_train, y_train)

# Saving nb_classifier for tfidf_vectorizer
pickle.dump(nb_classifier, open("pklFilescontents/nb_classifier_for_tfidf_vectorizer.pkl", "wb"))

In [11]:
# Prediction
pred = nb_classifier.predict(tfidf_X_test)

In [13]:
# Accuracy Score & Confusion Matrix

# Required Library
from sklearn import metrics

print("Multinomial Naive Bayes : (TF-IDF Approach) \n")

# Accuracy
a_score = metrics.accuracy_score(y_test, pred)
print("Accuracy : " + str("{:.2f}".format(a_score*100)),'%')

print("\n")

# Confusion Matrix
# Labels : 0(Business), 1(Entertainment), 2(Health), 3(Science & Technology)
# By defualt, Horizontally, Labels are from 0 to 3
# By defualt, Vertically,   Labels are from 0 to 3
confusion_matrix = metrics.confusion_matrix(y_test, pred)

print("Confusion Matrix :")
print(confusion_matrix)

Multinomial Naive Bayes : (TF-IDF Approach) 

Accuracy : 66.67 %


Confusion Matrix :
[[0 0 0 0 0 3]
 [0 3 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 0 2]
 [0 0 0 0 0 1]]


In [14]:
# Laplace Smoothing (Tunning parameter - alpha)

# List of alphas
alphas = np.arange(0,1,0.1)

# Function for training nb_classifier with different alpha values
def train_and_predict(alpha):
    
    # Instantiating Naive Bayes Classifier
    nb_classifier = MultinomialNB(alpha=alpha)
    
    # Fitting nb_classifier to Training Data
    nb_classifier.fit(tfidf_X_train, y_train)
    
    # Prediction
    pred = nb_classifier.predict(tfidf_X_test)
    
    # Accuracy Score
    a_score = metrics.accuracy_score(y_test, pred)
    
    return a_score


# Iterating over alphas & printing the corresponding Accuracy Score
for alpha in alphas:
    print("Alpha : ", alpha)
    print("Accuracy Score : ", train_and_predict(alpha))
    print()

Alpha :  0.0
Accuracy Score :  0.5333333333333333

Alpha :  0.1
Accuracy Score :  0.6

Alpha :  0.2
Accuracy Score :  0.6

Alpha :  0.30000000000000004
Accuracy Score :  0.6

Alpha :  0.4
Accuracy Score :  0.6666666666666666

Alpha :  0.5
Accuracy Score :  0.6666666666666666

Alpha :  0.6000000000000001
Accuracy Score :  0.6666666666666666

Alpha :  0.7000000000000001
Accuracy Score :  0.6666666666666666

Alpha :  0.8
Accuracy Score :  0.6666666666666666

Alpha :  0.9
Accuracy Score :  0.6666666666666666



C:\Users\SMIT\anaconda3\Lib\site-packages\sklearn\naive_bayes.py:624: FutureWarning: The default value for `force_alpha` will change to `True` in 1.4. To suppress this warning, manually set the value of `force_alpha`.
  warnings.warn(
C:\Users\SMIT\anaconda3\Lib\site-packages\sklearn\naive_bayes.py:633: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(


bag of words

In [16]:
# Feature Extraction

# Required Library
from sklearn.feature_extraction.text import CountVectorizer

# Instantiating CountVectorizer
count_vectorizer = CountVectorizer()

# Fitting & Tranforming Training Data (X_train)
count_X_train = count_vectorizer.fit_transform(X_train.values)

# Tranforming Testing Data (X_test)
count_X_test = count_vectorizer.transform(X_test.values)

# Saving count_vectorizer
pickle.dump(count_vectorizer, open("pklFilescontents/count_vectorizer.pkl","wb"))

In [17]:
# Multinomial Naive Bayes Classifier

# Required Library
from sklearn.naive_bayes import MultinomialNB

# Instantiating Naive Bayes Classifier with alpha = 1.0
nb_classifier = MultinomialNB()

# Fitting nb_classifier to Training Data
nb_classifier.fit(count_X_train, y_train)

# Saving nb_classifier for count_vectorizer
pickle.dump(nb_classifier, open("pklFilescontents/nb_classifier_for_count_vectorizer.pkl", "wb"))

In [18]:
# Prediction
pred = nb_classifier.predict(count_X_test)
# Accuracy Score & Confusion Matrix

# Required Library
from sklearn import metrics

print("Multinomial Naive Bayes : (BOW Approach) \n")

# Accuracy
a_score = metrics.accuracy_score(y_test, pred)
print("Accuracy : " + str("{:.2f}".format(a_score*100)),'%')

print("\n")

# Confusion Matrix
# Labels : 0(Business), 1(Entertainment), 2(Health), 3(Science & Technology)
# By defualt, Horizontally, Labels are from 0 to 3
# By defualt, Vertically,   Labels are from 0 to 3
confusion_matrix = metrics.confusion_matrix(y_test, pred)

print("Confusion Matrix :")
print(confusion_matrix)

Multinomial Naive Bayes : (BOW Approach) 

Accuracy : 53.33 %


Confusion Matrix :
[[0 0 0 0 0 3]
 [1 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 3 0 0]
 [1 0 0 0 0 1]
 [1 0 0 0 0 0]]


In [19]:

# Laplace Smoothing (Tunning parameter - alpha)

# List of alphas
alphas = np.arange(0,1,0.1)

# Function for training nb_classifier with different alpha values
def train_and_predict(alpha):
    
    # Instantiating Naive Bayes Classifier
    nb_classifier = MultinomialNB(alpha=alpha)
    
    # Fitting nb_classifier to Training Data
    nb_classifier.fit(count_X_train, y_train)
    
    # Prediction
    pred = nb_classifier.predict(count_X_test)
    
    # Accuracy Score
    a_score = metrics.accuracy_score(y_test, pred)
    
    return a_score


# Iterating over alphas & printing the corresponding Accuracy Score
for alpha in alphas:
    print("Alpha : ", alpha)
    print("Accuracy Score : ", train_and_predict(alpha))
    print()

Alpha :  0.0
Accuracy Score :  0.6666666666666666

Alpha :  0.1
Accuracy Score :  0.6

Alpha :  0.2
Accuracy Score :  0.6

Alpha :  0.30000000000000004
Accuracy Score :  0.6

Alpha :  0.4
Accuracy Score :  0.6

Alpha :  0.5
Accuracy Score :  0.6

Alpha :  0.6000000000000001
Accuracy Score :  0.5333333333333333

Alpha :  0.7000000000000001
Accuracy Score :  0.5333333333333333

Alpha :  0.8
Accuracy Score :  0.5333333333333333

Alpha :  0.9
Accuracy Score :  0.5333333333333333



C:\Users\SMIT\anaconda3\Lib\site-packages\sklearn\naive_bayes.py:624: FutureWarning: The default value for `force_alpha` will change to `True` in 1.4. To suppress this warning, manually set the value of `force_alpha`.
  warnings.warn(
C:\Users\SMIT\anaconda3\Lib\site-packages\sklearn\naive_bayes.py:633: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
